version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql_12
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
